const dataTechnologys = [
  {
    id: 0,
    images: 'https://logodownload.org/wp-content/uploads/2016/10/html5-logo-10.png',
    content: 'Html5',
    width: '22px',
    alt: 'Logo do Html',
    url: 'https://github.com/Pedro0505?tab=repositories&q=&type=&language=html&sort=',
  },
  {
    id: 1,
    images: 'https://logospng.org/download/css-3/logo-css-3-2048.png',
    content: 'CSS',
    width: '25px',
    alt: 'Logo do CSS',
    url: 'https://github.com/Pedro0505?tab=repositories&q=&type=&language=javascript&sort=',
  },
  {
    id: 2,
    images: 'https://digitalents.com.br/wp-content/uploads/2016/03/js-logo.png',
    content: 'JavaScript',
    width: '24px',
    alt: 'Logo do JavaScript',
    url: 'https://github.com/Pedro0505?tab=repositories&q=&type=&language=javascript&sort=',
  },
  {
    id: 3,
    images: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/react/react-original.svg',
    content: 'React',
    width: '26px',
    alt: 'Logo do React',
    url: 'https://github.com/Pedro0505?tab=repositories&q=&type=&language=javascript&sort=',
  },
  {
    id: 4,
    images: 'https://cdn-icons-png.flaticon.com/512/25/25231.png',
    content: 'GitHub',
    width: '22px',
    alt: 'Logo do GitHub',
    url: 'https://github.com/Pedro0505?tab=repositories&q=&type=&language=javascript&sort=',
  },
  {
    id: 5,
    images: 'https://git-scm.com/images/logos/downloads/Git-Icon-1788C.png',
    content: 'Git',
    width: '22px',
    alt: 'Logo do Git',
    url: 'https://github.com/Pedro0505?tab=repositories&q=&type=&language=javascript&sort=',
  },
  {
    id: 6,
    images: 'http://assets.stickpng.com/images/5848309bcef1014c0b5e4a9a.png',
    content: 'Redux',
    width: '22px',
    alt: 'Logo do Redux',
    url: 'https://github.com/Pedro0505?tab=repositories&q=&type=&language=javascript&sort=',
  },
];

export default dataTechnologys;
